### ISSUE TITLE
Missing defense field in GCG attack for gpt-4-0125-preview

### ISSUE THREAD

**Issue by ed1d1a8d** [JailbreakBench/artifacts#1]
https://github.com/JailbreakBench/artifacts/blob/93eb42d5afdbe01cabff7d262331727724562244/attack-artifacts/GCG/transfer/gpt-4-0125-preview.json#L5

Compare with https://github.com/JailbreakBench/artifacts/blob/93eb42d5afdbe01cabff7d262331727724562244/attack-artifacts/GCG/transfer/gpt-3.5-turbo-1106.json#L6C10-L6C25

**Comment by patrickrchao** [comment]
Thanks for this subtle catch! The artifacts are updated with the missing defense field now.
